
all: */*.java
	javac -cp ".:wrangLR.jar" */*.java

clean:
	rm -f errorMsg/*.class
	rm -f main/*.class
	rm -f syntaxtree/*.class
	rm -f visitor/ASTGenVisitor.class
	rm -f visitor/CodeStream.class
	rm -f visitor/TreeDrawerVisitor.class
	rm -f visitor/CG1Visitor.class
	rm -f visitor/ConstEvalVisitor.class
	rm -f visitor/Visitor.class
	rm -f visitor/CG2Visitor.class
	rm -f visitor/InitPredefined.class
	rm -f visitor/Visitor2.class
	rm -f visitor/CG3Visitor.class
	rm -f visitor/PrettyPrintVisitor.class
